[profile.default]
auto_detect_remappings = true
remappings = [
    "@chainlink/contracts/ = ../lib/chainlink-brownie-contracts/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol",
]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
